### ISSUE TITLE
Weather Data

### ISSUE THREAD

**Issue by transiteration** [rosia-lab/crop-forecasting#1]
Hello!
Where did you get the weather data for districts? Was it provided by the challenge organizer or using some outside data?
Thank you!

**Comment by louisreberga** [comment]
Hello, here is the website we used to get the weather data for districts: https://www.visualcrossing.com/weather-data

The dataset includes more fields, but the followings are the used by our model:
name: name of the location (Chau Phu, Chau Thanh or Thoai Son)
datetime: date and time of the weather observation (used to join the data)
tempmax: maximum temperature in Celsius for the day
tempmin: minimum temperature in Celsius for the day
temp: temperature in Celsius at the time of the observation
dew: dew point in Celsius at the time of the observation
humidity: relative humidity percentage at the time of the observation
precip: precipitation amount in millimeters
precipprob: probability of precipitation as a percentage
precipcover: percentage of the sky covered by precipitation
windspeed: wind speed in kilometers per hour
winddir: wind direction in degrees
sealevelpressure: sea level pressure in hectopascals
cloudcover: percentage of the sky covered
solarradiation: solar radiation in watts per square meter
solarenergy: solar energy output in kilowatt hours per square meter per day
uvindex: UV index
severerisk: risk of severe weather as a percentage
sunrise: time of sunrise for the day
sunset: time of sunset for the day
moonphase: phase of the moon

**Comment by transiteration** [comment]
Thanks for the detailed answer! Really appreciate it
